"""add confirmed field to managedresults

Revision ID: 57987a415db1
Revises: 3b423d1e443d
Create Date: 2014-03-12 06:33:11.732000

"""

# revision identifiers, used by Alembic.
revision = '57987a415db1'
down_revision = '3b423d1e443d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managedresult', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managedresult', 'confirmed')
    ### end Alembic commands ###
