"""normalize time fields in managedresult

Revision ID: f40369e94ad
Revises: 4b05b4289d07
Create Date: 2014-03-04 16:01:14.671000

"""

# revision identifiers, used by Alembic.
revision = 'f40369e94ad'
down_revision = '4b05b4289d07'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managedresult', sa.Column('time', sa.Float(), nullable=True))
    op.drop_column('managedresult', 'chiptime')
    op.drop_column('managedresult', 'guntime')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managedresult', sa.Column('guntime', mysql.FLOAT(), nullable=True))
    op.add_column('managedresult', sa.Column('chiptime', mysql.FLOAT(), nullable=True))
    op.drop_column('managedresult', 'time')
    ### end Alembic commands ###
