services:
  celery:
    ports:
      - 5678:5678
    environment:
      - FLASK_APP=/app/celery.py
    volumes:
      - ./app/src:/app
    # re -Xfrozen_modules=off, see https://stackoverflow.com/a/75347466
    command: ["sh", "-c", "pip install debugpy -t /tmp && python -Xfrozen_modules=off /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask --app celery -A rrwebapp.celery worker -l info -c 1 -f ${APP_LOGGING_PATH}/celery.%i.log -n scoretility.com"]
