"""series: add oaawards, divawards

Revision ID: 5604f6cad64c
Revises: 77442fc8e343
Create Date: 2021-12-15 06:50:04.520230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5604f6cad64c'
down_revision = '77442fc8e343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('divawards', sa.Integer(), nullable=True))
    op.add_column('series', sa.Column('oaawards', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'oaawards')
    op.drop_column('series', 'divawards')
    # ### end Alembic commands ###
