"""course table club_id, alias table, race table hidden, role and user table updates for flask-security

Revision ID: 7d3595961ca1
Revises: e175fb986917
Create Date: 2016-11-10 14:39:07.694000

"""

# revision identifiers, used by Alembic.
revision = '7d3595961ca1'
down_revision = 'e175fb986917'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

#added
from sqlalchemy.sql import table, column

# note we need the id to identify rows when column requires data specific to the row
raceresult = table('raceresult',
               column('hidden', sa.Boolean),
              )
#end added

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('club_id', sa.Integer(), nullable=True))
    op.drop_index('source', table_name='course')
    op.create_unique_constraint(None, 'course', ['club_id', 'source', 'sourceid'])
    op.create_foreign_key(None, 'course', 'club', ['club_id'], ['id'])
    op.alter_column('divisions', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('managedresult', 'confirmed',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('managedresult', 'initialdisposition',
               existing_type=mysql.ENUM('definite', 'similar', 'missed', 'excluded', ''),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('race', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('race', 'external',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('raceresult', sa.Column('hidden', sa.Boolean(), nullable=True))
    op.alter_column('raceresult', 'fuzzyage',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('raceresult', 'instandings',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('raceseries', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('role', sa.Column('description', sa.String(length=255), nullable=True))
    op.alter_column('role', 'name',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('runner', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('runner', 'member',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('series', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('series', 'allowties',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('series', 'averagetie',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('series', 'calcagegrade',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('series', 'calcdivisions',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('series', 'calcoverall',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('series', 'hightolow',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('series', 'maxbynumrunners',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('series', 'membersonly',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('user', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('current_login_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('current_login_ip', sa.String(length=39), nullable=True))
    op.add_column('user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login_ip', sa.String(length=39), nullable=True))
    op.add_column('user', sa.Column('login_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=True))
    op.alter_column('user', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_column('user', 'pwresetrequired')
    ### end Alembic commands ###

    # added
    op.execute(raceresult.update().values({
        'hidden':op.inline_literal(False), 
        }))
    # end added

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pwresetrequired', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)
    op.alter_column('user', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('user', 'password')
    op.drop_column('user', 'login_count')
    op.drop_column('user', 'last_login_ip')
    op.drop_column('user', 'last_login_at')
    op.drop_column('user', 'current_login_ip')
    op.drop_column('user', 'current_login_at')
    op.drop_column('user', 'confirmed_at')
    op.alter_column('series', 'membersonly',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('series', 'maxbynumrunners',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('series', 'hightolow',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('series', 'calcoverall',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('series', 'calcdivisions',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('series', 'calcagegrade',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('series', 'averagetie',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('series', 'allowties',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('series', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('runner', 'member',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('runner', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('role', 'name',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_column('role', 'description')
    op.alter_column('raceseries', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('raceresult', 'instandings',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('raceresult', 'fuzzyage',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('raceresult', 'hidden')
    op.alter_column('race', 'external',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('race', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('managedresult', 'initialdisposition',
               existing_type=sa.String(length=15),
               type_=mysql.ENUM('definite', 'similar', 'missed', 'excluded', ''),
               existing_nullable=True)
    op.alter_column('managedresult', 'confirmed',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('divisions', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_constraint(None, 'course', type_='unique')
    op.create_index('source', 'course', ['source', 'sourceid'], unique=True)
    op.drop_column('course', 'club_id')
    ### end Alembic commands ###
