"""series: add minraces, tieoptions

Revision ID: 86f57ce8ce48
Revises: 5604f6cad64c
Create Date: 2021-12-18 14:05:56.799261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f57ce8ce48'
down_revision = '5604f6cad64c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('minraces', sa.Integer(), nullable=True))
    op.add_column('series', sa.Column('tieoptions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'tieoptions')
    op.drop_column('series', 'minraces')
    # ### end Alembic commands ###
