"""managedresult.place is float, add runneralias table

Revision ID: b26c8d433967
Revises: 164e21263bd6
Create Date: 2016-12-21 06:46:35.106000

"""

# revision identifiers, used by Alembic.
revision = 'b26c8d433967'
down_revision = '164e21263bd6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runneralias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('runnerid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.ForeignKeyConstraint(['runnerid'], ['runner.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'club_id')
    )

    op.alter_column(u'managedresult', 'place',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=True)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(u'managedresult', 'place',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    op.drop_table('runneralias')
    ### end Alembic commands ###
